Описание задачи
Многие знают про маркетплейсы где продаются б/у вещи, на которых есть возможность недорого купить качественную и полезную вещь. Но всегда волнует вопрос - кто и как устанавливает цену, и какие его характеристики больше всего влияют на итоговую стоимость продажи?! Вопрос становиться особо актуальным, если речь идет про дорогие товары, например про автомобили!
Предлагаем вам принять участие в Мастерской, в рамках которой вы сможете поработать с данными о продажах автомобилей на вторичном рынке. Целью вашего проекта будет разработанная модель предсказания стоимости автомобиля на вторичном рынке.

описание данных

Date: Год выпуска автомобиля.

Make: Марка автомобиля.

Model: Модель автомобиля определенной марки.

Trim: Модификации автомобиля.

Body: Тип кузова транспортного средства относится к форме и модели конкретной марки автомобиля.

Transmission: Тип коробки передач.

VIN: Идентификационный номер транспортного средства.

State: Штат регистрации автомобиля

Condition: Состояние автомобилей на момент аукциона.

Odometer: Пробег - расстояние, пройденное автомобилем с момента выпуска.

Color: Цвет кузова автомобиля.

Interior: Цвет салона автомобиля.

Seller: Продавец автомобиля, автосалоны.

sellingprice: цена, по которой автомобиль был продан на аукционе.

saledate: Дата продажи автомобиля.

In [1]:
import math
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from numpy.random import RandomState
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.dummy import DummyClassifier


from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.model_selection import GridSearchCV
import warnings
from sklearn.model_selection import train_test_split
warnings.filterwarnings("ignore")

In [2]:
data_test = pd.read_csv('C:/Users/SuperUser/Downloads/test.csv')
data_train = pd.read_csv('C:/Users/SuperUser/Downloads/train.csv')

In [3]:
display(data_train.head())
display(data_train.info())
data_train.describe()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,sellingprice,saledate
0,2011,Ford,Edge,SEL,suv,automatic,2fmdk3jc4bba41556,md,4.2,111041.0,black,black,santander consumer,12500,Tue Jun 02 2015 02:30:00 GMT-0700 (PDT)
1,2014,Ford,Fusion,SE,Sedan,automatic,3fa6p0h75er208976,mo,3.5,31034.0,black,black,ars/avis budget group,14500,Wed Feb 25 2015 02:00:00 GMT-0800 (PST)
2,2012,Nissan,Sentra,2.0 SL,sedan,automatic,3n1ab6ap4cl698412,nj,2.2,35619.0,black,black,nissan-infiniti lt,9100,Wed Jun 10 2015 02:30:00 GMT-0700 (PDT)
3,2003,HUMMER,H2,Base,suv,automatic,5grgn23u93h101360,tx,2.8,131301.0,gold,beige,wichita falls ford lin inc,13300,Wed Jun 17 2015 03:00:00 GMT-0700 (PDT)
4,2007,Ford,Fusion,SEL,Sedan,automatic,3fahp08z17r268380,md,2.0,127709.0,black,black,purple heart,1300,Tue Feb 03 2015 04:00:00 GMT-0800 (PST)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440236 entries, 0 to 440235
Data columns (total 15 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   year          440236 non-null  int64
 1   make          432193 non-null  object
 2   model         432113 non-null  object
 3   trim          431899 non-null  object
 4   body          429843 non-null  object
 5   transmission  388775 non-null  object
 6   vin           440236 non-null  object
 7   state         440236 non-null  object
 8   condition     430831 non-null  float64
 9   odometer      440167 non-null  float64
 10  color         439650 non-null  object
 11  interior      439650 non-null  object
 12  seller        440236 non-null  object
 13  sellingprice  440236 non-null  int64
 14  saledate      440236 non-null  object
dtypes: float64(2), int64(2), object(11)
memory usage: 50.4+ MB

None

                year      condition       odometer   sellingprice
count  440236.000000  430831.000000  440167.000000  440236.000000
mean     2010.040101       3.425077   68344.421604   13592.209588
std         3.977945       0.949973   53542.203908    9751.479098
min      1982.000000       1.000000       1.000000       1.000000
25%      2007.000000       2.700000   28258.000000    6900.000000
50%      2012.000000       3.600000   52098.000000   12100.000000
75%      2013.000000       4.200000   99272.000000   18200.000000
max      2015.000000       5.000000  999999.000000  230000.000000

In [4]:
display(data_test.head())
display(data_test.info())
data_test.describe()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,saledate
0,2005,Cadillac,CTS,Base,Sedan,automatic,1g6dp567450124779,ca,2.7,116970.0,silver,black,lexus of stevens creek,Wed Jan 14 2015 04:30:00 GMT-0800 (PST)
1,2014,GMC,Savana Cargo,2500,Van,NaN,1gtw7fca7e1902207,pa,4.4,6286.0,white,gray,u-haul,Fri Feb 27 2015 01:00:00 GMT-0800 (PST)
2,2013,Nissan,Murano,S,SUV,automatic,jn8az1mw6dw303497,oh,4.6,11831.0,gray,black,nissan-infiniti lt,Tue Feb 24 2015 01:30:00 GMT-0800 (PST)
3,2013,Chevrolet,Impala,LS Fleet,Sedan,automatic,2g1wf5e34d1160703,fl,2.3,57105.0,silver,black,onemain rem/auto club of miami inc dba north dad,Fri Mar 06 2015 02:00:00 GMT-0800 (PST)
4,2013,Nissan,Titan,SV,Crew Cab,automatic,1n6aa0ec3dn301209,tn,2.9,31083.0,black,black,nissan north america inc.,Wed Jun 03 2015 03:30:00 GMT-0700 (PDT)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110058 entries, 0 to 110057
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   year          110058 non-null  int64
 1   make          107997 non-null  object
 2   model         107979 non-null  object
 3   trim          107944 non-null  object
 4   body          107464 non-null  object
 5   transmission  97047 non-null   object
 6   vin           110058 non-null  object
 7   state         110058 non-null  object
 8   condition     107679 non-null  float64
 9   odometer      110039 non-null  float64
 10  color         109900 non-null  object
 11  interior      109900 non-null  object
 12  seller        110058 non-null  object
 13  saledate      110058 non-null  object
dtypes: float64(2), int64(1), object(11)
memory usage: 11.8+ MB

None

                year      condition       odometer
count  110058.000000  107679.000000  110039.000000
mean     2010.060005       3.423222   68074.331601
std         3.960190       0.951301   53520.988173
min      1982.000000       1.000000       1.000000
25%      2007.000000       2.700000   28313.500000
50%      2012.000000       3.600000   51922.000000
75%      2013.000000       4.200000   98852.500000
max      2015.000000       5.000000  999999.000000

In [5]:
data_train['make'].unique()

array(['Ford', 'Nissan', 'HUMMER', 'Lincoln', 'pontiac', 'Hyundai', nan,
       'Buick', 'Chevrolet', 'Honda', 'Acura', 'Cadillac', 'GMC', 'Saab',
       'Dodge', 'Mercedes-Benz', 'Toyota', 'Volkswagen', 'BMW',
       'Infiniti', 'Chrysler', 'Kia', 'Jaguar', 'Subaru', 'Jeep', 'Lexus',
       'mercedes', 'Scion', 'FIAT', 'Suzuki', 'Mazda', 'Volvo', 'Audi',
       'MINI', 'Isuzu', 'Mitsubishi', 'smart', 'Pontiac', 'Porsche',
       'subaru', 'ford', 'Land Rover', 'chrysler', 'Saturn', 'mazda',
       'dodge', 'Ram', 'Oldsmobile', 'hyundai', 'Mercury', 'Bentley',
       'toyota', 'lincoln', 'Fisker', 'nissan', 'chevrolet', 'honda',
       'porsche', 'mitsubishi', 'lexus', 'bmw', 'Maserati', 'acura',
       'jeep', 'mercury', 'Tesla', 'landrover', 'vw', 'cadillac', 'buick',
       'gmc truck', 'land rover', 'volkswagen', 'Rolls-Royce', 'audi',
       'Ferrari', 'suzuki', 'Plymouth', 'oldsmobile', 'Lamborghini',
       'gmc', 'Geo', 'ford truck', 'Aston Martin', 'plymouth', 'Daewoo',
       'maserati', 'kia', 'mercedes-b', 'dodge tk', 'mazda tk', 'dot',
       'airstream'], dtype=object)

In [6]:
data_test['make'].unique()

array(['Cadillac', 'GMC', 'Nissan', 'Chevrolet', 'Volkswagen', 'Hyundai',
       'Ford', 'Infiniti', 'Subaru', 'Kia', 'BMW', nan, 'Mitsubishi',
       'Dodge', 'Oldsmobile', 'Volvo', 'Pontiac', 'Acura', 'Honda',
       'Toyota', 'Audi', 'Jeep', 'Lincoln', 'Chrysler', 'Mercedes-Benz',
       'Ram', 'Scion', 'Mercury', 'Lexus', 'Saturn', 'Mazda', 'Porsche',
       'MINI', 'smart', 'Buick', 'HUMMER', 'ford', 'chrysler', 'Jaguar',
       'mitsubishi', 'FIAT', 'Saab', 'mazda', 'Suzuki', 'Land Rover',
       'bmw', 'cadillac', 'oldsmobile', 'honda', 'acura', 'buick',
       'landrover', 'Geo', 'lexus', 'dodge', 'chevrolet', 'chev truck',
       'nissan', 'Bentley', 'jeep', 'mercury', 'toyota', 'gmc', 'Isuzu',
       'Aston Martin', 'Maserati', 'land rover', 'kia', 'subaru',
       'Daewoo', 'vw', 'volkswagen', 'Tesla', 'mercedes', 'Ferrari',
       'hyundai', 'pontiac', 'Fisker', 'porsche', 'Rolls-Royce', 'Lotus',
       'Plymouth', 'hyundai tk', 'lincoln', 'ford tk', 'audi'],
      dtype=object)

In [7]:
print(data_test.duplicated().sum())
print(data_train.duplicated().sum())

0
0

In [8]:
data_test['model'].unique()

array(['CTS', 'Savana Cargo', 'Murano', 'Impala', 'Titan', 'Passat',
       'Sonata', 'Explorer', 'G Sedan', 'Suburban', 'Forester', 'Escape',
       'Fiesta', 'Taurus', 'Forte', '6 Series', 'TrailBlazer',
       'Silverado 1500', 'Genesis', 'Equinox', nan, 'Lancer',
       'E-Series Wagon', 'Grand Caravan', 'Focus', 'Alero', 'XC60',
       'Montana', 'Fusion', 'Soul', 'TSX', 'G6', 'Accord', 'Maxima',
       'Camry', 'Sierra 1500', 'A6', 'Camaro', 'RAV4', 'Corolla', 'XC70',
       'Compass', 'Expedition', 'Jetta', 'CR-V', 'LS', 'Odyssey',
       'Transit Connect', 'Optima', 'Traverse', 'F-150', 'Elantra',
       'Altima', 'S6', 'Sorento', 'G35', 'M', 'FJ Cruiser',
       'Town and Country', 'Civic', 'C-Class', 'Avenger', '1500', 'FR-S',
       'X3', '300', 'Magnum', 'F-350 Super Duty', 'STS', 'G Coupe',
       'Terrain', 'Spectra', 'Cruze', 'Journey', 'Tucson', 'Tundra',
       'Malibu', 'Grand Cherokee', 'Grand Marquis', 'Sedona', 'RX 350',
       'A4', 'LS 460', '3 Series', 'X5', 'Yaris', 'ION', 'TL',
       'Econoline Cargo', 'G37 Coupe', 'Juke', 'Versa', 'MKZ',
       'Ram Pickup 1500', 'Acadia', 'IS 250', 'Elantra GT', 'X1', 'Envoy',
       'Venza', 'Frontier', 'Tahoe', 'Accent', 'GS 350', 'Liberty',
       'Sonic', 'CX-5', 'Malibu Hybrid', 'xB', 'GL-Class', '911', 'Dart',
       'Escalade', 'Mazda3', 'Mazda6', 'MKX', 'Pathfinder',
       'E-Series Van', 'Mustang', 'CX-7', 'Charger', 'Sentra', 'Edge',
       '4Runner', 'Quest', 'Sable', 'FX', 'Prius', 'S-Class', 'Caliber',
       'Escalade ESV', 'Freestar', 'Rogue', 'CLK-Class', 'Wrangler',
       'Cooper', 'Tiburon', 'fortwo', 'Element', '5 Series',
       'Econoline Wagon', 'Flex', 'Tacoma', 'Ranger', 'Azera', 'R-Class',
       'Galant', 'Yukon', 'Cobalt', 'Ram Pickup 3500', 'CT 200h',
       'SL-Class', 'Century', 'Rogue Select', 'Rendezvous', 'Mazda5',
       'Seville', 'GS 300', 'Fusion Hybrid', 'Patriot', 'Mariner',
       '7 Series', 'Stratus', 'M3', 'H3', 'explorer', 'MDX', 'LX 470',
       'G8', 'Sonata Hybrid', 'twn&country', 'Challenger', '200',
       'Sienna', 'LS 430', 'Pilot', 'Aspen', 'Prius c', 'Rio',
       'XJ-Series', 'Highlander', 'Colorado', 'DeVille', 'S40', 'Q5',
       'Land Cruiser', 'expeditn', 'tC', 'IS 350', 'galant', 'Fit',
       'Mazda2', 'Outlander Sport', 'Camry Solara', 'Camry Hybrid',
       'X-Type', 'ATS', 'Nitro', 'Lucerne', 'F-250 Super Duty', 'ES 350',
       'E-Class', 'Enclave', 'Outback', 'F-150 Heritage',
       'Silverado 3500HD', 'Express Cargo', 'NV Cargo', 'Outlander',
       'LX 570', 'Tiguan', 'Tribute', 'Uplander', '500L', 'M5', 'QX4',
       'Yukon XL', 'CLA-Class', 'Z4', 'Captiva Sport', 'Mirage', 'G37',
       'HHR', 'Aztek', '3500', 'M-Class', 'RDX', 'C/V Cargo Van', 'XC90',
       'Cayenne', '9-5', 'Silverado 2500HD', 'Expedition EL', 'QX60',
       'New Beetle', 'Grand Am', 'Impreza', 'Explorer Sport', 'Beetle',
       'mazda6', 'RX 330', 'Dakota', 'Boxster', 'S60', 'CTS Coupe',
       'Corvette', 'Insight', 'Five Hundred', 'Commander', 'Sequoia',
       'GLK-Class', 'iQ', 'Legacy', 'Freestyle', 'VUE', 'Santa Fe',
       'Monte Carlo', 'Leaf', 'ILX', 'Aveo', 'Malibu Maxx', 'Cadenza',
       'Astro Cargo', 'S-Series', 'Vibe', 'C70', 'Q7', 'Ridgeline', 'M35',
       'LeSabre', 'Grand Prix', 'Regal', 'Avalon', 'SLK-Class', 'XF',
       'escape', 'PT Cruiser', 'Genesis Coupe', 'Versa Note',
       'Eclipse Spyder', 'Impala Limited', 'Sierra 2500HD',
       'Corvette Stingray', 'Xterra', 'Sebring', 'Town Car', 'MKC', 'GTI',
       'Cooper Countryman', 'GLI', 'CX-9', 'Protege', 'Durango',
       'Veloster', 'LaCrosse', 'Cooper Clubman', 'RX 450h', 'Milan',
       'Forenza', 'Golf', 'QX', 'Aura', '2500', 'MKS', 'S-10', '2 Series',
       'Accord Crosstour', 'Navigator', 'SX4', 'Beetle Convertible',
       'IS 250 C', 'Sportage', 'ES 300', 'XL-7', 'V70', 'SRX', '6',
       'Intrigue', 'QX80', 'Highlander Hybrid', 'CLS-Class',
       'Elantra Touring', 'H2', 'GX 460', '9-3', 'SC 400', 'L-Series',
       'FX35', 'Lancer Sportback', 'RX 400h', 'Cube', 'DTS', 'JX',
       'ES 330', 'Reno', 'xD', 'XK', 'B9 Tribeca', 'Armada', 'Sonoma',
       'Sky', 'Bravada', 'Avalanche', '500', 'Volt', 'Park Avenue',
       'F-450 Super Duty', 'Amanti', 'Eclipse', 'MKT', 'Solstice',
       'Equus', 'S-10 Blazer', 'Matrix', 'XJ', 'Murano CrossCabriolet',
       'Sprinter Cargo', 'Range Rover Evoque', 'Promaster Cargo Van',
       'Mountaineer', 'Touareg', 'QX56', 'Caravan', 'Tracker', 'endeavor',
       'Savana', 'EX', 'Jetta SportWagen', 'Cavalier', 'Ram Pickup 2500',
       'Torrent', '300M', 'Cherokee', 'Outlook', 'I30', 'I35', 'LR4',
       'M45', 'Blazer', 'V60', '750li', 'A5', 'Tercel', 'G-Class', 'S80',
       'TrailBlazer EXT', 'G Convertible', 'Celica', '626', 'Veracruz',
       'Spark', 'Santa Fe Sport', 'Range Rover Sport', 'Q50',
       'Range Rover', 'Silverado 1500 Classic', 'Aurora', 'EX35', 'RLX',
       'Grand Vitara', 'Rondo', 'A8', 'XV Crosstrek', 'LS 400', 'RX 300',
       'GT-R', 'S-Type', 'XL7', 'Panamera', 'L300', 'srx', '370Z',
       'Sunfire', 'XTS', 'Elantra Coupe', 'silhouette',
       'Lancer Evolution', 'Escape Hybrid', 'RS 5', 'Endeavor', 'Prius v',
       'Excursion', 'Impreza WRX', 'Aviator', 'Neon', 'RSX',
       'Cooper Paceman', 'CL-Class', 'X6', 'Routan', 'Canyon',
       'Crown Victoria', 'Concorde', 'Verano', '3', 'Raider',
       'Q60 Convertible', 'XG350', 'Windstar', 'pilot', 'Zephyr',
       'Q60 Coupe', 'Freelander', 'rl', '350Z', 'S5', 'rx8', 'Montero',
       'MX-5 Miata', 'Golf R', 'allure', 'BRZ', 'Mariner Hybrid',
       'Borrego', 'lr3', 'CC', 'Explorer Sport Trac', 'Q45', 'CR-Z',
       'Express', '4 Series', 'Prizm', 'Fusion Energi',
       'Silverado 1500HD', 'gx', 'Encore', 'LR2', '750i', 'TT',
       '6 Series Gran Coupe', 'caravan', 'corvette', 'Relay', 'Crosstour',
       'Envoy XL', 'K900', 'Silverado 2500', 'Protege5', 'Pacifica',
       '5 Series Gran Turismo', 's10', '350z', 'RS 6', 'C-Max Hybrid',
       'malibu', 'Classic', 'Avalon Hybrid', 'Silverado 3500', 'A3',
       'Sierra 3500', 'VUE Hybrid', 'NV', 'cx-7', 'expedition',
       'Continental GTC', 'CTS-V Coupe', 'Taurus X', 'Montego',
       'Sierra 3500HD', 'MPV', 'R8', 'Integra', 'Transit Wagon', 'Lumina',
       'Mazdaspeed 3', 'GS 430', 'ZDX', 'M6', 'Catera', 'QX70', 'ECHO',
       'wrangler', 'hhr', 'Mazdaspeed Protege', 'Terraza',
       'TSX Sport Wagon', 'IS 300', 'Silverado 2500HD Classic', 'C30',
       '9-7X', 'villager', 'Altima Hybrid', 'lx', 'Focus ST', 'Crossfire',
       'Millenia', 'Intrepid', 'stratus', 'tundra', 'Yukon Hybrid',
       '1 Series', 'x-trail', 'Rabbit', 'gr', 'M37', 'IS 350 C', 'Escort',
       'G20', 'i-MiEV', 'V40', 'WRX', 'Tahoe Hybrid', 'S4', 'V50',
       'H2 SUT', 'pacifica', 'Eos', 'C-Max Energi', 'Jetta GLI', 'alp',
       'Escalade Hybrid', 'Sprinter', 'S70', 'Sierra 1500 Classic',
       'Firebird', 'C/K 2500 Series', 'Thunderbird', 'Monterey',
       'Cutlass', 'A7', 'accord', 'Escalade EXT', 'Venture', 'GX 470',
       'M4', 'C/K 1500 Series', 'RC 350', 'Rainier', 'Rodeo', '850',
       'Passport', 'Q70', 'M56', 'G5', 'XC', 'venture', 'F-TYPE',
       'V8 Vantage', 'Silhouette', 'LHS', 'Mark LT', 'Equator', 'Tribeca',
       'GranTurismo Convertible', 'Blackwood', 'Sierra 2500HD Classic',
       'discovery', 'Jimmy', 'e350', 'range', 'Cayman', 'Prelude',
       'Trooper', 'uplander', 'borrego', 'Mazdaspeed Mazda6',
       'B-Series Pickup', 'Continental GT', 'XK-Series', 'colorado',
       'Truck', 'CTS-V', 'Quattroporte', 'X6 M', 'Achieva', 'forester',
       'cobalt', 'Bonneville', 'G3', 'RX-8', 'Z3', 'allroad quattro',
       'Montero Sport', 'GTO', 'mazda5', 'Shelby GT500', 'Villager',
       'compass', 'SSR', 'Kizashi', 'Navigator L', 'Envoy XUV',
       'Cooper Coupe', 'Prius Plug-in', 'envoy', 'RL', 'Eldorado',
       'S2000', 'e', 'SC 430', 'mpv', 'Leganza', 'Ram Cargo',
       'Rodeo Sport', 'routan', 'magnum', 'FX45', 'CL', 'intrepid', 'S8',
       'Cougar', 'Cooper Roadster', 'R32', 'LR3', 'Tahoe Limited/Z71',
       'sebring', 'Discovery Series II', 'beetle', 'Nubira', 'durango',
       'grand', 'Model S', 'dakota', 'windstar', 'ES 300h', 'c230wz',
       'Entourage', 'XG300', 'Continental', 'freestyle', 'GranTurismo',
       'e150', 'F430', 'allroad', 'MKZ Hybrid', 'santa', 'XLR', 'f150',
       'g3500', 'Baja', 'Pickup', 'xA', 'Cutlass Supreme', 'Voyager',
       'Contour', 'f250', 'Astro', 'ActiveHybrid 5',
       '4 Series Gran Coupe', 'Jetta Hybrid', 'town', 'regal',
       'Yukon Denali', 'odyssey', 'alero', 'Malibu Classic',
       '3 Series Gran Turismo', 'g1500', 'astro', 'Astra', 'Golf GTI',
       'MR2 Spyder', 'Ghibli', 'rangerover', 'i-Series', 'NV200', 'SQ5',
       'S7', 'GS 400', 'Mazdaspeed3', 'Cutlass Ciera', 'sts',
       'G37 Convertible', 'HS 250h', 'B-Series Truck', 'b1500',
       'Ascender', 'yaris', 'sprinter', 'ram3500', 'SS', 'vibe',
       'Continental Flying Spur', 'Aerio', 'X4', 'journey', 'Axiom',
       'bronco', 'impala', 'H3T', 'B-Class Electric Drive', 'Sephia',
       'Karma', 'ranger', 'Mazdaspeed Mazda3', 'dts', '9-2X', 'Touareg 2',
       'Black Diamond Avalanche', 'Mustang SVT Cobra', 'GS 450h',
       'Diamante', 'Sierra 1500HD', 'X5 M', 'GranSport', 'montana',
       'Cayman S', 'Transit Van', 'Accord Hybrid', 'rio', 'tribute',
       'c240w', 'ridgelin', 'Ghost', '1', 'Exige', 'el', 'jetta', 'f350',
       'Viper', 'sienna', 'CTS Wagon', 'QX50', 'LS 600h L', 'Tempo',
       'FX50', 'Cirrus', 'i8', 'elantra', 'Vitara', 'patriot', 'mdx',
       'corolla', 'STS-V', 'g5', '350', 'g6', 'C/V Tradesman', '300ZX',
       'e250', 'M6 Gran Coupe', 'Flying Spur', 'previa', 'eurovan',
       'focus', 'RC F', 'Prowler', 'mkt', 'Cabrio', 'S90', 'RS 7',
       'taurus', 'ciera', 'a6', 'IS F', 'Eighty-Eight', 'Verona', '360',
       's55', 'Marauder', '300-Class', 'suburban', '300e', 'TLX',
       'Tracer', 'police', 'Breeze', 'thunderbird', 'ActiveHybrid X6',
       'SLS AMG GT', 'Macan', 'Phaeton', 'F-150 SVT Lightning',
       'Grand Cherokee SRT', '200SX', 'tt', 'charger', 'pathfind',
       'Aspire', 'Milan Hybrid', 'Sidekick', 'SC 300', 'civic', 'sonic',
       'Sierra 1500 Hybrid', '3000GT', 'x3', 'E-150', 'Riviera',
       'Eighty-Eight Royale', 'quest', 'pursuit',
       'Continental Flying Spur Speed', 'lancer', 'Caprice'], dtype=object)

In [9]:
data_train['model'].unique()

array(['Edge', 'Fusion', 'Sentra', 'H2', 'MKZ', 'g6', 'Escape', 'Elantra',
       'Freestyle', nan, 'Lucerne', 'Windstar', 'Silverado 1500',
       'Murano', 'Equinox', 'Accord', 'Civic', 'MDX', 'CTS', 'Taurus',
       'SRX', 'Yukon', '9-3', 'Explorer', 'F-150', 'Charger', 'Armada',
       'GL-Class', 'Avalon', 'Tahoe', 'Malibu', 'Passat', 'Camry', 'Flex',
       '3 Series', 'Q50', 'Altima', 'Mustang', '300', 'Sonata',
       'Envoy XL', 'Rogue', 'Accent', 'Maxima', 'Forte', 'XF', 'Outback',
       'Grand Caravan', 'E-Class', 'Cherokee', 'Impala', 'Optima',
       '5 Series', 'Expedition', 'IS 250', 'MKS', '200', 'Veloster',
       'Golf', 'RAV4', 'e300dt', 'Five Hundred', 'G Coupe',
       'Grand Cherokee', 'X-Type', 'G Convertible', 'Tacoma', 'xA',
       'G Sedan', 'TL', 'Liberty', 'Soul', '500L', 'Town and Country',
       'HHR', 'Wrangler', 'Reno', 'Suburban', 'PT Cruiser', 'GX 460',
       'Sienna', 'SL-Class', 'Envoy', 'Patriot', 'E-Series Van', 'Versa',
       'Aspen', 'M', 'Colorado', 'Beetle', 'Spark', 'RX 330',
       'Rendezvous', 'Town Car', '1 Series', 'Venture', 'Corolla',
       'Focus', 'MKX', 'MX-5 Miata', 'Traverse', 'Pathfinder',
       'Silverado 2500HD', 'Ram Pickup 1500', 'S60', 'A6',
       'TSX Sport Wagon', 'Fusion Hybrid', '4Runner', 'Sorento', 'RX 300',
       'Explorer Sport Trac', 'Nitro', '7 Series', 'Q7', 'Odyssey',
       'Camaro', 'X5', 'M3', 'Caliber', 'I35', 'Journey',
       '5 Series Gran Turismo', 'Prius', 'Regal', 'Cooper Countryman',
       'Jetta', 'malibu', 'Avenger', 'Cooper', 'Camry Hybrid', 'Rodeo',
       'F-250 Super Duty', 'RX 350', 'Cruze', 'TSX', 'XJ-Series',
       'Savana Cargo', 'Mazda5', 'Escalade', 'Challenger',
       'Express Cargo', 'R-Class', 'M-Class', 'C-Class', 'Tiburon',
       'Outlander', 'CR-V', 'XC90', 'Legacy', 'Sierra 1500', 'LaCrosse',
       'Eclipse', 'RSX', 'ES 350', 'Sportage', 'Avalanche', 'Highlander',
       'Corvette', 'Sonata Hybrid', 'Ranger', 'Navigator', 'Aveo',
       'Fiesta', 'TrailBlazer', 'Cube', 'Pilot', 'fortwo', 'Galant',
       'Century', 'Tucson', 'G6', 'Highlander Hybrid', 'Magnum',
       'F-350 Super Duty', 'Elantra Touring', 'Silverado 3500HD',
       'Uplander', 'CX-5', 'Commander', 'Compass', 'Rogue Select',
       'c230wz', 'CTS Coupe', 'LS', 'Outlander Sport', 'Terrain',
       'Mazda3', 'H3', '911', 'forester', 'Impala Limited', 'Durango',
       'Land Cruiser', 'XC', 'SLK-Class', 'Insight', '6 Series',
       'CLS-Class', 'f150', 'S-Type', 'Panamera', 'Frontier', 'X3',
       'Enclave', 'Range Rover Sport', 'Sonic', 'Crown Victoria', 'Rio',
       'Dart', 'E-Series Wagon', 'Mazda6', 'Dakota', 'pacifica', 'Matrix',
       'Sebring', 'G5', '500', 'Freestar', 'GS 350', 'M45', 'G35',
       'Cobalt', 'Forenza', 'Transit Connect', 'VUE', 'Torrent', 'ION',
       'Neon', 'DeVille', '370Z', 'S-10', 'cx-7', 'LR4', 'A4', 'grand',
       'Econoline Cargo', '1500', 'Impreza', 'Cadenza',
       'F-450 Super Duty', 'Camry Solara', 'Touareg', 'A7', 'LS 430',
       'Fit', 'DTS', 'Kizashi', 'Prizm', 'Santa Fe', 'Cavalier',
       'LeSabre', 'FX', 'Cutlass Ciera', 'tC', 'Jetta SportWagen',
       'S-Class', 'Element', 'Expedition EL', 'Elantra Coupe',
       'GLK-Class', 'FX35', 'Yaris', 'X6', 'Sequoia', 'Astro', 'LX 570',
       'Acadia', 'Cooper Paceman', '4 Series', 'FJ Cruiser', 'RL', 'Volt',
       'Grand Prix', '2500', 'Sierra 2500HD', 'IS 350', 'Verano', 'santa',
       'CX-9', 'Tundra', 'Yukon XL', 'accord', 'Tiguan',
       'Ram Pickup 2500', 'Spectra', 'Lumina', 'xD', 'Astra',
       'Silverado 1500 Classic', 'Mountaineer', 'Quest', 'Tribute',
       'Captiva Sport', 'Sonoma', 'Sable', 'XJ', 'Leaf',
       'Continental GTC', 'Titan', 'Forester', 'Sierra 3500HD', 'Xterra',
       'Range Rover', 'Venza', 'New Beetle', 'CX-7', 'Escort', 'Express',
       'CT 200h', 'sienna', 'Escalade ESV', 'QX80', 'GTI', 'QX',
       'Crosstour', 'Cooper Clubman', 'Mazda2', 'ES 330', 'Lancer',
       'Genesis', 'Grand Vitara', 'Outlook', 'NV Cargo', 'Caravan',
       'XK-Series', 'Protege', 'JX', 'Aura', 'Vibe', 'F-TYPE', 'Grand Am',
       'CL', '300M', 'C-Max Hybrid', 'Mirage', 'Santa Fe Sport', 'QX56',
       'Sedona', 'S40', 'Juke', 'ES 300h', 'durango', 'xB',
       'Eclipse Spyder', 'Milan', 'M35', 'C-Max Energi', 'Mariner', 'Z4',
       'Malibu Classic', 'Cayenne', 'GS 300', 'Sprinter', 'Intrepid',
       'town', 'LS 460', 'ILX', 'L-Series', 'QX60', 'S-Series', 'S4',
       'I30', 'Altima Hybrid', 'S80', '6', 'Escape Hybrid', 'Monterey',
       'Genesis Coupe', 'Caprice', 'Pacifica', 'Stratus', 'V70', 'Tercel',
       'FR-S', 'Prius v', 'Continental GT', 'STS', 'Millenia', 'Z3',
       'Accord Crosstour', 'Rainier', 'CLK-Class', 'Elantra GT',
       'Endeavor', 'Monte Carlo', 'Cougar', 'Karma', 'Rabbit', 'CC',
       'ATS', 'G-Class', 'RX 450h', 'Ram Pickup 3500', 'Boxster', 'Azera',
       'G37', 'C70', 'XV Crosstrek', '3500', '350z', 'TT', 'venture',
       'Zephyr', '3 Series Gran Turismo', 'XL-7', 'XC60', 'SX4',
       'Ridgeline', '9-7X', 'Bravada', 'g5', 'XL7', 'MPV', '9-5', 'Jimmy',
       'RX 400h', 'Escalade EXT', 'Versa Note', 'EX35', 'A8', 'quest',
       'A5', 'S7', 'B9 Tribeca', 'Crossfire', 'Bonneville',
       'Grand Marquis', 'Shelby GT500', 'impala', 'Canyon',
       'Explorer Sport', 'allroad quattro', 'Aviator',
       '4 Series Gran Coupe', 'Taurus X', 'CL-Class', 'RDX',
       'Continental', 'Q5', 'Alero', 'Cayman', 'pilot', 'V40',
       'G37 Coupe', 'Aurora', 'expeditn', 'Beetle Convertible', 'X1',
       'M6', 'galant', 'Escalade Hybrid', 'CLA-Class', 'Solstice',
       'IS 300', 'Eos', 'TrailBlazer EXT', 'Lancer Sportback', 'tribute',
       'XK', 'LX 470', 'Malibu Maxx', 'Routan', 'ES 300', 'gx',
       'Entourage', 'Lancer Evolution', 'X6 M', 'Blazer', 'Ascender',
       '750i', 'Montero', 'Sierra 1500 Classic', 'CV Tradesman', '350Z',
       'S5', 'Rondo', 'A3', 'EX', 'XTS', 'Quattroporte', 'Prius c',
       'Tracker', 'GranTurismo', 'M5', 'legacy', 'MKT',
       'Corvette Stingray', 'LHS', 'Veracruz', 'Impreza WRX', 'Equus',
       'M37', 'Trooper', 'Sunfire', 'ELR', 'WRX', 'C/V Cargo Van', 'XC70',
       'iQ', '960', 'ActiveHybrid X6', 'Tribeca', 'Montero Sport',
       'Excursion', '6 Series Gran Coupe', 'Econoline Wagon', 'SC 430',
       'GX 470', 'Fusion Energi', 'rl', '2 Series', 'QX4', 'J30',
       'Freelander', 'Silverado 3500', 'Encore', 'GT-R', 'Amanti',
       'Seville', '3', 'IS 250 C', 'Mustang SVT Cobra',
       'Silverado 2500HD Classic', 'Borrego', 'cobalt', '300ZX',
       'Integra', 'explorer', 'GS 450h', 'ECHO', 'S90', 'Sephia',
       'Classic', 'Concorde', 'GS 460', 'Q60 Coupe', 'Avalon Hybrid',
       'Sky', 'lx', 'F-150 Heritage', 'allroad', 'Promaster Cargo Van',
       'patriot', 'hhr', 'mpv', 'Malibu Hybrid', 'Sprinter Cargo',
       'ram3500', 'police', 'corvette', 'Model S', 'Firebird', 'SC 400',
       'HS 250h', 'wrangler', 'XG350', 'Cabrio', 'Mazdaspeed 3',
       'Focus ST', 'matrix', 'lr3', 'GS 400', 'gr', 'Protege5', 'G8',
       'L300', 'RS 7', 'Aerio', 'S70', 'GS 430', 'Intrigue', 'X4',
       'Thunderbird', 'Diamante', 'LR2', 'H2 SUT', 'SSR',
       'Discovery Series II', 'Envoy XUV', 'Montana', 'i8', '626',
       'tundra', 'CTS-V Coupe', 'e350', 'routan', 'V60', 'SC 300',
       'x-trail', 'XG300', 'QX70', 'Celica', 'Cooper Coupe', 'srx',
       'Silverado 1500HD', 'BRZ', 'Prowler', 'ZDX', 'Cirrus', 'camaro',
       'Mazdaspeed Mazda3', 'ridgelin', '750li', 'Cutlass Supreme',
       'Jetta Hybrid', 'CTS Wagon', 'Range Rover Evoque', 'IS F', 'C30',
       'CTS-V', 'Macan', 'ranger', 'R8', 'RC 350', 'CR-Z', 'journey',
       'Q70', 'Continental Flying Spur', 'Golf GTI', 'Spyder', '320i',
       'B-Series Truck', 'V50', 'Relay', 'e150', 'excurs',
       'G37 Convertible', 'e', 'Montego', 'RLX', 'FX45', 'Cayman S',
       'ActiveHybrid 7', 'expedition', 'C/K 3500 Series', 'Montana SV6',
       'Legend', 'caravan', 'Eldorado', 'M6 Gran Coupe', 'Mark VIII',
       'VUE Hybrid', 'Voyager', 'Yukon Hybrid', 'Q45', 'envoy',
       'Mariner Hybrid', 'mkt', 'Park Avenue', 'century', 'Passport',
       'RS 6', 'Prius Plug-in', 'endeavor', 'el', 'sr', 'Golf R',
       'MR2 Spyder', 'G20', 'Navigator L', 'taurus', 'Astro Cargo',
       'Transit Van', '940', 'compass', 'R32', 'Discovery',
       'Murano CrossCabriolet', 'S2000', 'range', 'Q60 Convertible',
       'GLI', 'LS 400', 'mazda3', 'K900', 'Mark LT', 'MKC', 'QX50',
       'passat', 'Silverado 2500', 'Villager', 'Ghost', 'Tahoe Hybrid',
       'a4', 'Baja', 'c240w', 'Viper', 'mazda5', 'F430', 'M4', 'NV',
       'Ghibli', 'g3500', 'GTO', 'crown', 'avalon', 'odyssey', 'Contour',
       '500-Class', 'Pickup', 'regal', 'Verona', 'Cabriolet', 'LR3',
       'Mazdaspeed3', 'Silhouette', 'Marauder', 'escape', 'yaris',
       'magnum', 'lancer', 'Terraza', 'Sierra 2500HD Classic',
       'California', 'discovery', 'Truck', 'Jetta GLI', 'alero', 'Aztek',
       'windstar', 'Vitara', 'Touareg 2', 'yukon', 'Sierra 3500',
       'sebring', 'rx8', 'Axiom', 'previa', 'C/K 1500 Series', 'Gallardo',
       'sprinter', 'Catera', 'stratus', 'ActiveHybrid 5', 'TTS', 'sts',
       'MKZ Hybrid', 'g55', 'C/V Tradesman', 'X5 M', 'Coupe', 'STS-V',
       'Prelude', 'XLR', 'NV200', 'G3', 'IS 350 C', 'Tahoe Limited/Z71',
       'twn/cntry', 'pt', 'concorde', 'Savana', 'Black Diamond Avalanche',
       'mountaineer', 'Tracer', 'GLA-Class', 'ram', '850', 'swift', 'H3T',
       '42c', 'Rodeo Sport', '500e', 'mdx', 'E-250', 'S8', 'Raider',
       'equinox', 'sonoma', '300-Class', 'RS 4', 'elantra',
       'Continental GT Speed', 'Milan Hybrid', 'Tribute Hybrid',
       'Cutlass', 'pathfinder', 'Eighty-Eight', 'E-150', 'Blackwood',
       'Accord Hybrid', 'i-MiEV', 'villager', 'Mazdaspeed Mazda6',
       'i-Series', 'Transit Wagon', 'Sierra 1500 Hybrid', 'RC F',
       'rangerover', 'uplander', 'Safari Cargo', 'comm',
       'B-Series Pickup', 'Phaeton', 'Esteem', 'Mazdaspeed Protege',
       'V8 Vantage', 's10', 'S6', 'SQ5', 'LS 600h L', 'Q3', 'astro',
       'Cooper Roadster', 'cl55', 'e250', 'f250', 'charger', '3000GT',
       'RS 5', 'Safari', 'S-10 Blazer', 'voyager', 'g1500', 'alp',
       'Eighty-Eight Royale', 'rainier', 's55', '200SX', '750lxi',
       'EuroVan', 'escalade', 'RX-8', 'FX50', 'Ram Van',
       'GranTurismo Convertible', 'DB9', 'savana', 'Nubira',
       'Windstar Cargo', 'crossfire', '420-Class', 'Roadmaster', 'ciera',
       'b1500', 'quattroporte', 'sportage', 'F-150 SVT Lightning',
       'cavalier', 'jetta', 'B-Class Electric Drive',
       'Mazdaspeed MX-5 Miata', 'Ram Cargo', 'dakota', 'twn&country',
       'civic', 'safari', 'Aura Hybrid', 'Silverado 1500 Hybrid',
       'montana', 'M56', 'camry', 'sl55', 'neon', 'carrera', 'f350',
       'expedit', 'Z4 M', 'NV Passenger', 'freestyle', 'Yukon Denali',
       'Sierra 1500HD', 'Silverado 3500 Classic', 'beetle', '8 Series',
       '9-2X', 'sx4', 'Regency', 'Sierra 2500', 'g2500', 'pickup',
       'corolla', 'TT RS', 'pathfind', 'Tempo', 'Civic del Sol', 'siera',
       'mazda6', 'rr', 'thunderbird', 'intrigue', 'b200', '400-Class',
       'ML55 AMG', 'golf', 'Corsica', 'rio', 'Breeze',
       'Continental GTC Speed', 'tahoe', 'pursuit', 'optra', 'borrego',
       'Fleetwood', 'dts', 'colorado', 'LX 450', 'subrbn', 'Riviera',
       'E-350', 'capt', 'cherokee', 'eurovan', 'SLS AMG', '190-Class',
       'cougar', '328i', '300e', 'SS', 'c230', 'rrs', 'Mystique',
       'optima', 'wave', 'lumina', 'Flying Spur', '323i', 'uplandr',
       'intrepid', 'Paseo', 'Le Baron', 'C/K 2500 Series', 'T100',
       '420sel', 'Amigo', 'Spark EV', 'aveo', 'Aspire', 'cruze', '7',
       'H1', 'b2300', 'Spirit', 'suburban', 'focus', 'breeze', 'Rapide',
       'Equator', 'silhouette', 'corsica', 'vibe', 'sonic', 'mountnr',
       'lacrosse', 'B-Series', 'Continental Flying Spur Speed',
       'interstate', 'c240s', 'CTS-V Wagon', '458 Italia', 'versa',
       'Metro', 'Continental Supersports', 'avenger', 'a6', 'F-250',
       'tucson', 'GranSport', 'g500'], dtype=object)

In [10]:
data_test.head()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,saledate
0,2005,Cadillac,CTS,Base,Sedan,automatic,1g6dp567450124779,ca,2.7,116970.0,silver,black,lexus of stevens creek,Wed Jan 14 2015 04:30:00 GMT-0800 (PST)
1,2014,GMC,Savana Cargo,2500,Van,NaN,1gtw7fca7e1902207,pa,4.4,6286.0,white,gray,u-haul,Fri Feb 27 2015 01:00:00 GMT-0800 (PST)
2,2013,Nissan,Murano,S,SUV,automatic,jn8az1mw6dw303497,oh,4.6,11831.0,gray,black,nissan-infiniti lt,Tue Feb 24 2015 01:30:00 GMT-0800 (PST)
3,2013,Chevrolet,Impala,LS Fleet,Sedan,automatic,2g1wf5e34d1160703,fl,2.3,57105.0,silver,black,onemain rem/auto club of miami inc dba north dad,Fri Mar 06 2015 02:00:00 GMT-0800 (PST)
4,2013,Nissan,Titan,SV,Crew Cab,automatic,1n6aa0ec3dn301209,tn,2.9,31083.0,black,black,nissan north america inc.,Wed Jun 03 2015 03:30:00 GMT-0700 (PDT)

In [11]:
data_test.duplicated().sum()

0

In [12]:
data_test.nunique()

year                31
make                85
model              824
trim              1496
body                77
transmission         2
vin             110058
state               38
condition           41
odometer         77205
color               20
interior            17
seller            7623
saledate          2817
dtype: int64

In [13]:
def exploratory(data_test):
    print(f"Shape:    {data_test.shape}")
    print("Na's:         ", data_test.isna().sum().sum())
    print("duplicates:   ", data_test.duplicated().sum())
    plt.show()

In [14]:
exploratory(data_test)

Shape:    (110058, 14)
Na's:          24573
duplicates:    0

In [15]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440236 entries, 0 to 440235
Data columns (total 15 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   year          440236 non-null  int64
 1   make          432193 non-null  object
 2   model         432113 non-null  object
 3   trim          431899 non-null  object
 4   body          429843 non-null  object
 5   transmission  388775 non-null  object
 6   vin           440236 non-null  object
 7   state         440236 non-null  object
 8   condition     430831 non-null  float64
 9   odometer      440167 non-null  float64
 10  color         439650 non-null  object
 11  interior      439650 non-null  object
 12  seller        440236 non-null  object
 13  sellingprice  440236 non-null  int64
 14  saledate      440236 non-null  object
dtypes: float64(2), int64(2), object(11)
memory usage: 50.4+ MB

In [16]:
data_train['condition'] = data_train['condition']. fillna (0)

In [17]:
data_train['odometer'] = data_train['odometer']. fillna (0)

vin - идентификатор автомобиля в тестовом наборе.
sellingprice - Целевой признак. Для каждого автомобиля предскажите числовое значение стоимости продажи.

In [18]:
#отделим целевой признак от выборок
features_train = data_train.drop('sellingprice', axis=1)
target_train = data_train['sellingprice']

In [19]:
df_train_obj = data_train.select_dtypes(['object'])
data_train[df_train_obj.columns] = df_train_obj.apply(lambda x: x.str.strip())

In [20]:
cols = data_train.columns[data_train.dtypes.eq('float64')]

data_train[cols] = data_train[cols].astype('int')

In [21]:
cols = data_train.columns[data_train.dtypes.eq('float64')]

data_train[cols] = data_train[cols].astype('int')

In [22]:
columns_OH = ['year',
             'condition',
             'odometer']

In [23]:
ohe_train = features_train.drop(columns_OH, axis=1)

In [24]:
scaler = StandardScaler()
scaler.fit(features_train[columns_OH])

StandardScaler()

In [25]:

features_train_scaled = pd.DataFrame(scaler.transform(features_train[columns_OH]),
                                     index=features_train[columns_OH].index,
                                     columns=features_train[columns_OH].columns)

features_train_scaled = features_train_scaled.join(ohe_train)
features_train_scaled.head()

,year,condition,odometer,make,model,trim,body,transmission,vin,state,color,interior,seller,saledate
0,0.241305,0.798375,0.797599,Ford,Edge,SEL,suv,automatic,2fmdk3jc4bba41556,md,black,black,santander consumer,Tue Jun 02 2015 02:30:00 GMT-0700 (PDT)
1,0.995464,0.139413,-0.696608,Ford,Fusion,SE,Sedan,automatic,3fa6p0h75er208976,mo,black,black,ars/avis budget group,Wed Feb 25 2015 02:00:00 GMT-0800 (PST)
2,0.492692,-1.084374,-0.610978,Nissan,Sentra,2.0 SL,sedan,automatic,3n1ab6ap4cl698412,nj,black,black,nissan-infiniti lt,Wed Jun 10 2015 02:30:00 GMT-0700 (PDT)
3,-1.769785,-0.519549,1.175974,HUMMER,H2,Base,suv,automatic,5grgn23u93h101360,tx,gold,beige,wichita falls ford lin inc,Wed Jun 17 2015 03:00:00 GMT-0700 (PDT)
4,-0.764240,-1.272648,1.108890,Ford,Fusion,SEL,Sedan,automatic,3fahp08z17r268380,md,black,black,purple heart,Tue Feb 03 2015 04:00:00 GMT-0800 (PST)

In [26]:
from sklearn.metrics import make_scorer
from sklearn.metrics import f1_score
from sklearn.model_selection import cross_val_score
scorer = make_scorer(f1_score, zero_division=0)

In [28]:
model = LogisticRegression(random_state=12345, class_weight='balanced')
scores = cross_val_score(model, features_train_scaled, target_train, scoring='f1')
best_logistic_result1 = sum(scores)/len(scores)
print('Наилучший средний результат :', best_logistic_result1)

ValueError:
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1196, in fit
    X, y = self._validate_data(
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\base.py", line 565, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 1106, in check_X_y
    X = check_array(
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 879, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\utils\_array_api.py", line 185, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\pandas\core\generic.py", line 2070, in __array__
    return np.asarray(self._values, dtype=dtype)
ValueError: could not convert string to float: 'Toyota'

--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1196, in fit
    X, y = self._validate_data(
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\base.py", line 565, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 1106, in check_X_y
    X = check_array(
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 879, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\utils\_array_api.py", line 185, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\pandas\core\generic.py", line 2070, in __array__
    return np.asarray(self._values, dtype=dtype)
ValueError: could not convert string to float: 'Ford'

вот эта ошибка на всех моделях, я так и не поняла как ее убрать...

In [29]:
best_tree_model = None
best_tree_result1 = 0

for depth in range (1, 15):
    model = DecisionTreeClassifier(random_state=12345, max_depth=depth,class_weight='balanced')
    result = np.mean(cross_val_score(model, features_train_scaled, target_train, cv=5, scoring='f1'))
    if result > best_tree_result1:
        best_tree_model = model
        best_tree_result1 = result
        best_tree_depth1 = depth
print('Наилучший результат:',best_tree_result1)
print('Наилучшая глубина дерева:',best_tree_depth1)

ValueError:
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 889, in fit
    super().fit(
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 186, in fit
    X, y = self._validate_data(
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\base.py", line 560, in _validate_data
    X = check_array(X, input_name="X", **check_X_params)
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 879, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\utils\_array_api.py", line 185, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\pandas\core\generic.py", line 2070, in __array__
    return np.asarray(self._values, dtype=dtype)
ValueError: could not convert string to float: 'Toyota'

--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 889, in fit
    super().fit(
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 186, in fit
    X, y = self._validate_data(
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\base.py", line 560, in _validate_data
    X = check_array(X, input_name="X", **check_X_params)
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 879, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\utils\_array_api.py", line 185, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\pandas\core\generic.py", line 2070, in __array__
    return np.asarray(self._values, dtype=dtype)
ValueError: could not convert string to float: 'Ford'

In [30]:
best_forest_model = None
best_forest_result1 = 0
best_forest_est=0
best_forest_depth1=0

for est in range(10, 51, 10):
    for depth in range (1, 11):
        model = RandomForestClassifier(random_state=12345, n_estimators=est, max_depth=depth,class_weight='balanced')
        result = np.mean(cross_val_score(model, features_train_scaled, target_train, cv=5, scoring=scorer))
        if result > best_forest_result1:
            best_forest_model = model
            best_forest_result1 = result
            best_forest_est = est
            best_forest_depth1 = depth
print('Наилучший результат',best_forest_result1 )
print('Наилучшая глубина дерева:',best_forest_depth1)

ValueError:
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 345, in fit
    X, y = self._validate_data(
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\base.py", line 565, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 1106, in check_X_y
    X = check_array(
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 879, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\utils\_array_api.py", line 185, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\pandas\core\generic.py", line 2070, in __array__
    return np.asarray(self._values, dtype=dtype)
ValueError: could not convert string to float: 'Toyota'

--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 345, in fit
    X, y = self._validate_data(
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\base.py", line 565, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 1106, in check_X_y
    X = check_array(
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 879, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\sklearn\utils\_array_api.py", line 185, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
  File "C:\Users\SuperUser\anaconda3\lib\site-packages\pandas\core\generic.py", line 2070, in __array__
    return np.asarray(self._values, dtype=dtype)
ValueError: could not convert string to float: 'Ford'

In [31]:
results = [best_forest_result, best_tree_result, best_logistic_result]
result_df = pd.DataFrame([results],
                         columns=['Случайный лес', 'Дерево решений', 'Логистическая регрессия'],
                        index=['Результат'])
result_df

NameError: name 'best_forest_result' is not defined

In [ ]:
model = RandomForestClassifier(random_state=54321, n_estimators=est, max_depth=depth,class_weight='balanced')
model.fit(features_train, target_train)


predicted_test = model.predict(features_test)
probabilities_test = model.predict_proba(features_test)
probabilities_one_test = probabilities_test[:, 1]
test_f1_score = f1_score(target_test, predicted_test )
auc_roc = roc_auc_score(target_test, probabilities_one_test)


print ('Значение F1-меры на тестовой выборке:', test_f1_score) 
print ('Значение метрики AUC-ROC:', auc_roc)